# Site settings
name: Dima Sazonoff
email: dima.sazonoff3@gmail.com
#canonical_url: https://dimasazonoff.com
keywords: "Software Engineer, C++, C#, High Frequency Trading, Crypto currency trading, Python, Machine Learning, Startups, Agile"
skills: "Senior Software Engineer in New York, NY"
baseurl:

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
# You should replace these with your social networks, of course. :)
social:
  - title: linkedin
    url: https://www.linkedin.com/in/dima-sazonoff/
  - title: medium
    url: https://medium.com/@cgroom
  - title: twitter
    url: https://twitter.com/chuck_groom
    
# Google webmaster tools
google_verify:

# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 2196F3
  primary-rgb: "33, 150, 243"
  secondary: 285172
  secondary-dark: 29455b
  section-tout: eaf1f1



# Build settings
markdown: kramdown
permalink: pretty
